language: shell
os: linux

env:
  global:
    - IMAGE=registry.gitlab.com/modmyclassic/docker-autodevops-buildenvs/mmc-crosscompiler-docker-image:latest_internal
    - TARGETBUILD=vba_next_libretro
  jobs:
    - TARGET=nesc CLOUD_DIR=NESC
    - TARGET=psc CLOUD_DIR=PSC

services:
  - docker

before_script:
  - docker login -u ${GITLAB_USER} -p ${GITLAB_PASS} registry.gitlab.com
  - docker pull ${IMAGE}
  - docker run -it -d --name crosscomp ${IMAGE} bash
  - docker exec -it --privileged crosscomp bash -c "git clone --depth=50 --branch=master https://github.com/libretro/vba-next ${TRAVIS_REPO_SLUG}"

script:
  - docker exec -it --privileged crosscomp bash -c "cd ${TRAVIS_REPO_SLUG} && classic_make_${TARGET} Makefile.libretro clean"
  - docker exec -it --privileged crosscomp bash -c "cd ${TRAVIS_REPO_SLUG} && classic_make_${TARGET} Makefile.libretro"
  - docker exec -it --privileged crosscomp bash -c "chown 600 ~/.keys/release_private_key.pem"
  - docker exec -it --privileged crosscomp bash -c "find ${TRAVIS_REPO_SLUG} -name '*.so' -print -exec xz '{}' \; -exec mv '{}'.xz '{}' \;"
  - docker exec -it --privileged crosscomp bash -c "cd ${TRAVIS_REPO_SLUG} && echo -e  'cd /var/www/html/cores/Automated_Builds/${CLOUD_DIR}\nput ${TARGETBUILD}.so' | sftp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ~/.keys/release_private_key.pem docker@classicmodscloud.com"
